tomcat.connector.connectionTimeout=180000
tomcat.connector.keepAliveTimeout=180000
{{- $hostname := include "cred.hostname" . }}
{{- if $hostname }}
tomcat.connector.secure=true
tomcat.connector.scheme=https
tomcat.connector.proxyName={{ $hostname }}
tomcat.connector.proxyPort=443
{{- end }}
{{- with .Values.application.identityManagerClass }}
ca.nrc.cadc.auth.IdentityManager={{ . }}
{{- end }}
{{- if hasKey .Values.application "enableClientCertHeader" }}
ca.nrc.cadc.auth.PrincipalExtractor.enableClientCertHeader={{ .Values.application.enableClientCertHeader }}
{{- end }}
{{- if hasKey .Values.application "allowBasicATP" }}
ca.nrc.cadc.auth.PrincipalExtractor.allowBasicATP={{ .Values.application.allowBasicATP }}
{{- end }}
ca.nrc.cadc.util.Log4jInit.messageOnly=true
